#include <string_view_util.h>
#include "myctype.h"
#include "indep.h"
#include "gc_helper.h"
#include "html/html.h"
#include "entity.h"
#include "w3m.h"




/* parse HTML tag */
static std::unordered_map<std::string, HtmlTags> g_tagMap = {
    /* 0 */ {"option_int", HTML_OPTION_INT},
    /* 1 */ {"/form_int", HTML_N_FORM_INT},
    /* 2 */ {"/kbd", HTML_NOP},
    /* 3 */ {"dd", HTML_DD},
    /* 4 */ {"/dir", HTML_N_UL},
    /* 5 */ {"/body", HTML_N_BODY},
    /* 6 */ {"noframes", HTML_NOFRAMES},
    /* 7 */ {"bdo", HTML_BDO},
    /* 8 */ {"base", HTML_BASE},
    /* 9 */ {"/div", HTML_N_DIV},
    /* 10 */ {"big", HTML_BIG},
    /* 11 */ {"tbody", HTML_TBODY},
    /* 12 */ {"meta", HTML_META},
    /* 13 */ {"i", HTML_I},
    /* 14 */ {"label", HTML_LABEL},
    /* 15 */ {"/_symbol", HTML_N_SYMBOL},
    /* 16 */ {"sup", HTML_SUP},
    /* 17 */ {"/p", HTML_N_P},
    /* 18 */ {"/q", HTML_N_Q},
    /* 19 */ {"input_alt", HTML_INPUT_ALT},
    /* 20 */ {"dl", HTML_DL},
    /* 21 */ {"/tbody", HTML_N_TBODY},
    /* 22 */ {"/s", HTML_N_S},
    /* 23 */ {"/label", HTML_N_LABEL},
    /* 24 */ {"del", HTML_DEL},
    /* 25 */ {"xmp", HTML_XMP},
    /* 26 */ {"br", HTML_BR},
    /* 27 */ {"iframe", HTML_IFRAME},
    /* 28 */ {"link", HTML_LINK},
    /* 29 */ {"/u", HTML_N_U},
    /* 30 */ {"em", HTML_EM},
    /* 31 */ {"title_alt", HTML_TITLE_ALT},
    /* 32 */ {"caption", HTML_CAPTION},
    /* 33 */ {"plaintext", HTML_PLAINTEXT},
    /* 34 */ {"p", HTML_P},
    /* 35 */ {"q", HTML_Q},
    /* 36 */ {"blockquote", HTML_BLQ},
    /* 37 */ {"menu", HTML_UL},
    /* 38 */ {"fieldset", HTML_FIELDSET},
    /* 39 */ {"/colgroup", HTML_N_COLGROUP},
    /* 40 */ {"dfn", HTML_NOP},
    /* 41 */ {"s", HTML_S},
    /* 42 */ {"strong", HTML_STRONG},
    /* 43 */ {"dt", HTML_DT},
    /* 44 */ {"u", HTML_U},
    /* 45 */ {"/map", HTML_N_MAP},
    /* 46 */ {"/frameset", HTML_N_FRAMESET},
    /* 47 */ {"/ol", HTML_N_OL},
    /* 48 */ {"noscript", HTML_NOSCRIPT},
    /* 49 */ {"legend", HTML_LEGEND},
    /* 50 */ {"/td", HTML_N_TD},
    /* 51 */ {"li", HTML_LI},
    /* 52 */ {"html", HTML_BODY},
    /* 53 */ {"hr", HTML_HR},
    /* 54 */ {"/strong", HTML_N_STRONG},
    /* 55 */ {"small", HTML_SMALL},
    /* 56 */ {"/th", HTML_N_TH},
    /* 57 */ {"option", HTML_OPTION},
    /* 58 */ {"/span", HTML_N_SPAN},
    /* 59 */ {"kbd", HTML_NOP},
    /* 60 */ {"dir", HTML_UL},
    /* 61 */ {"col", HTML_COL},
    /* 62 */ {"param", HTML_PARAM},
    /* 63 */ {"/small", HTML_N_SMALL},
    /* 64 */ {"/legend", HTML_N_LEGEND},
    /* 65 */ {"/caption", HTML_N_CAPTION},
    /* 66 */ {"div", HTML_DIV},
    /* 67 */ {"/abbr", HTML_N_ABBR},
    /* 68 */ {"head", HTML_HEAD},
    /* 69 */ {"ol", HTML_OL},
    /* 70 */ {"/ul", HTML_N_UL},
    /* 71 */ {"/ins", HTML_N_INS},
    /* 72 */ {"area", HTML_AREA},
    /* 73 */ {"pre_plain", HTML_PRE_PLAIN},
    /* 74 */ {"button", HTML_BUTTON},
    /* 75 */ {"td", HTML_TD},
    /* 76 */ {"/option", HTML_N_OPTION},
    /* 77 */ {"/noframes", HTML_N_NOFRAMES},
    /* 78 */ {"/tr", HTML_N_TR},
    /* 79 */ {"nobr", HTML_NOBR},
    /* 80 */ {"img_alt", HTML_IMG_ALT},
    /* 81 */ {"table_alt", HTML_TABLE_ALT},
    /* 82 */ {"th", HTML_TH},
    /* 83 */ {"script", HTML_SCRIPT},
    /* 84 */ {"/tt", HTML_NOP},
    /* 85 */ {"code", HTML_NOP},
    /* 86 */ {"optgroup", HTML_OPTGROUP},
    /* 87 */ {"samp", HTML_NOP},
    /* 88 */ {"textarea", HTML_TEXTAREA},
    /* 89 */ {"textarea_int", HTML_TEXTAREA_INT},
    /* 90 */ {"table", HTML_TABLE},
    /* 91 */ {"img", HTML_IMG},
    /* 92 */ {"/blockquote", HTML_N_BLQ},
    /* 93 */ {"applet", HTML_APPLET},
    /* 94 */ {"map", HTML_MAP},
    /* 95 */ {"ul", HTML_UL},
    /* 96 */ {"basefont", HTML_BASEFONT},
    /* 97 */ {"/script", HTML_N_SCRIPT},
    /* 98 */ {"center", HTML_CENTER},
    /* 99 */ {"/table", HTML_N_TABLE},
    /* 100 */ {"cite", HTML_NOP},
    /* 101 */ {"/h1", HTML_N_H},
    /* 102 */ {"/fieldset", HTML_N_FIELDSET},
    /* 103 */ {"tr", HTML_TR},
    /* 104 */ {"/h2", HTML_N_H},
    /* 105 */ {"image", HTML_IMG},
    /* 106 */ {"/h3", HTML_N_H},
    /* 107 */ {"pre_int", HTML_PRE_INT},
    /* 108 */ {"/font", HTML_N_FONT},
    /* 109 */ {"tt", HTML_NOP},
    /* 110 */ {"/h4", HTML_N_H},
    /* 111 */ {"body", HTML_BODY},
    /* 112 */ {"/form", HTML_N_FORM},
    /* 113 */ {"/h5", HTML_N_H},
    /* 114 */ {"/h6", HTML_N_H},
    /* 115 */ {"frame", HTML_FRAME},
    /* 116 */ {"/textarea_int", HTML_N_TEXTAREA_INT},
    /* 117 */ {"/noscript", HTML_N_NOSCRIPT},
    /* 118 */ {"/img_alt", HTML_N_IMG_ALT},
    /* 119 */ {"/center", HTML_N_CENTER},
    /* 120 */ {"/pre", HTML_N_PRE},
    /* 121 */ {"tfoot", HTML_TFOOT},
    /* 122 */ {"ins", HTML_INS},
    /* 123 */ {"/var", HTML_NOP},
    /* 124 */ {"h1", HTML_H},
    /* 125 */ {"/tfoot", HTML_N_TFOOT},
    /* 126 */ {"input", HTML_INPUT},
    /* 127 */ {"h2", HTML_H},
    /* 128 */ {"h3", HTML_H},
    /* 129 */ {"h4", HTML_H},
    /* 130 */ {"h5", HTML_H},
    /* 131 */ {"internal", HTML_INTERNAL},
    /* 132 */ {"h6", HTML_H},
    /* 133 */ {"div_int", HTML_DIV_INT},
    /* 134 */ {"select_int", HTML_SELECT_INT},
    /* 135 */ {"/pre_int", HTML_N_PRE_INT},
    /* 136 */ {"/menu", HTML_N_UL},
    /* 137 */ {"form_int", HTML_FORM_INT},
    /* 138 */ {"/sub", HTML_N_SUB},
    /* 139 */ {"style", HTML_STYLE},
    /* 140 */ {"address", HTML_BR},
    /* 141 */ {"/optgroup", HTML_N_OPTGROUP},
    /* 142 */ {"/textarea", HTML_N_TEXTAREA},
    /* 143 */ {"/input_alt", HTML_N_INPUT_ALT},
    /* 144 */ {"span", HTML_SPAN},
    /* 145 */ {"doctype", HTML_DOCTYPE},
    /* 146 */ {"/style", HTML_N_STYLE},
    /* 147 */ {"/html", HTML_N_BODY},
    /* 148 */ {"pre", HTML_PRE},
    /* 149 */ {"title", HTML_TITLE},
    /* 150 */ {"abbr", HTML_ABBR},
    /* 151 */ {"select", HTML_SELECT},
    /* 152 */ {"/bdo", HTML_N_BDO},
    /* 153 */ {"acronym", HTML_ACRONYM},
    /* 154 */ {"/div_int", HTML_N_DIV_INT},
    /* 155 */ {"var", HTML_NOP},
    /* 156 */ {"/big", HTML_N_BIG},
    /* 157 */ {"/title", HTML_N_TITLE},
    /* 158 */ {"embed", HTML_EMBED},
    /* 159 */ {"/sup", HTML_N_SUP},
    /* 160 */ {"colgroup", HTML_COLGROUP},
    /* 161 */ {"/head", HTML_N_HEAD},
    /* 162 */ {"isindex", HTML_ISINDEX},
    /* 163 */ {"strike", HTML_S},
    /* 164 */ {"listing", HTML_LISTING},
    /* 165 */ {"bgsound", HTML_BGSOUND},
    /* 166 */ {"/address", HTML_BR},
    /* 167 */ {"object", HTML_OBJECT},
    /* 168 */ {"thead", HTML_THEAD},
    /* 169 */ {"wbr", HTML_WBR},
    /* 170 */ {"/del", HTML_N_DEL},
    /* 171 */ {"/nobr", HTML_N_NOBR},
    /* 172 */ {"/select", HTML_N_SELECT},
    /* 173 */ {"frameset", HTML_FRAMESET},
    /* 174 */ {"/xmp", HTML_N_XMP},
    /* 175 */ {"/code", HTML_NOP},
    /* 176 */ {"_symbol", HTML_SYMBOL},
    /* 177 */ {"/thead", HTML_N_THEAD},
    /* 178 */ {"/samp", HTML_NOP},
    /* 179 */ {"/dfn", HTML_NOP},
    /* 180 */ {"_id", HTML_NOP},
    /* 181 */ {"/strike", HTML_N_S},
    /* 182 */ {"/a", HTML_N_A},
    /* 183 */ {"/select_int", HTML_N_SELECT_INT},
    /* 184 */ {"sub", HTML_SUB},
    /* 185 */ {"/b", HTML_N_B},
    /* 186 */ {"/internal", HTML_N_INTERNAL},
    /* 187 */ {"/acronym", HTML_N_ACRONYM},
    /* 188 */ {"/pre_plain", HTML_N_PRE_PLAIN},
    /* 189 */ {"font", HTML_FONT},
    /* 190 */ {"/dl", HTML_N_DL},
    /* 191 */ {"form", HTML_FORM},
    /* 192 */ {"/cite", HTML_NOP},
    /* 193 */ {"a", HTML_A},
    /* 194 */ {"b", HTML_B},
    /* 195 */ {"/listing", HTML_N_LISTING},
    /* 196 */ {"/em", HTML_N_EM},
    /* 197 */ {"/i", HTML_N_I},
};

HtmlTags GetTag(const char *src, HtmlTags defaultValue)
{
    auto found = g_tagMap.find(src);
    if (found == g_tagMap.end())
    {
        return defaultValue;
    }
    return found->second;
}

