#pragma once
struct Line;
union InputStream;
struct AnchorList;
struct LinkList;
struct FormList;
struct MapList;
struct HmarkerList;
struct ParsedURL;
struct FormItemList;
struct BufferPos;
struct Buffer
{
    char *filename;
    char *buffername;
    Line *firstLine;
    Line *topLine;
    Line *currentLine;
    Line *lastLine;
    Buffer *nextBuffer;
    Buffer *linkBuffer[MAX_LB];
    short width;
    short height;
    char *type;
    const char *real_type;
    int allLine;
    short bufferprop;
    int currentColumn;
    short cursorX;
    short cursorY;
    int pos;
    int visualpos;
    short rootX;
    short rootY;
    short COLS;
    short LINES;
    InputStream *pagerSource;
    AnchorList *href;
    AnchorList *name;
    AnchorList *img;
    AnchorList *formitem;
    LinkList *linklist;
    FormList *formlist;
    MapList *maplist;
    HmarkerList *hmarklist;
    HmarkerList *imarklist;
    ParsedURL currentURL;
    ParsedURL *baseURL;
    char *baseTarget;
    int real_scheme;
    char *sourcefile;
    struct frameset *frameset;
    struct frameset_queue *frameQ;
    int *clone;
    size_t trbyte;
    char check_url;
    wc_ces document_charset;
    uint8_t auto_detect;
    TextList *document_header;
    FormItemList *form_submit;
    char *savecache;
    char *edit;
    struct mailcap *mailcap;
    char *mailcap_source;
    char *header_source;
    char search_header;
    char *ssl_certificate;
    char image_flag;
    char image_loaded;
    char need_reshape;
    Anchor *submit;
    BufferPos *undo;
    AlarmEvent *event;
};

void deleteImage(Buffer *buf);
void getAllImage(Buffer *buf);
void loadImage(Buffer *buf, int flag);
Anchor *registerForm(Buffer *buf, FormList *flist, struct parsed_tag *tag, int line, int pos);
MapArea *follow_map_menu(Buffer *buf, char *name, Anchor *a_img, int x,int y);
Buffer *nullBuffer(void);
void clearBuffer(Buffer *buf);
void discardBuffer(Buffer *buf);
Buffer *namedBuffer(Buffer *first, char *name);
Buffer *deleteBuffer(Buffer *first, Buffer *delbuf);
Buffer *replaceBuffer(Buffer *first, Buffer *delbuf, Buffer *newbuf);
Buffer *nthBuffer(Buffer *firstbuf, int n);
void gotoRealLine(Buffer *buf, int n);
void gotoLine(Buffer *buf, int n);
Buffer *selectBuffer(Buffer *firstbuf, Buffer *currentbuf,char *selectchar);
void reshapeBuffer(Buffer *buf);
void copyBuffer(Buffer *a, Buffer *b);
Buffer *prevBuffer(Buffer *first, Buffer *buf);
HmarkerList *putHmarker(HmarkerList *ml, int line, int pos, int seq);
void shiftAnchorPosition(AnchorList *a, HmarkerList *hl, int line,
                         int pos, int shift);
char *getAnchorText(Buffer *buf, AnchorList *al, Anchor *a);
void set_buffer_environ(Buffer *buf);
