#pragma once

#include "dispatcher.h"
#include "commands.h"

inline void register_commands()
{
  RegisterCommand("nulcmd", "NOTHING NULL @ @ @", "Do nothing", &nulcmd);
  RegisterCommand("escmap", "ESCMAP", "ESC map", &escmap);
  RegisterCommand("escbmap", "ESCBMAP", "ESC [ map", &escbmap);
  RegisterCommand("multimap", "MULTIMAP", "multimap", &multimap);
  RegisterCommand("pgFore", "NEXT_PAGE", "Move to next page", &pgFore);
  RegisterCommand("pgBack", "PREV_PAGE", "Move to previous page", &pgBack);
  RegisterCommand("lup1", "UP", "Scroll up one line", &lup1);
  RegisterCommand("ldown1", "DOWN", "Scroll down one line", &ldown1);
  RegisterCommand("ctrCsrV", "CENTER_V", "Move to the center column", &ctrCsrV);
  RegisterCommand("ctrCsrH", "CENTER_H", "Move to the center line", &ctrCsrH);
  RegisterCommand("rdrwSc", "REDRAW", "Redraw screen", &rdrwSc);
  RegisterCommand("srchfor", "SEARCH SEARCH_FORE WHEREIS", "Search forward", &srchfor);
  RegisterCommand("isrchfor", "ISEARCH", "Incremental search forward", &isrchfor);
  RegisterCommand("srchbak", "SEARCH_BACK", "Search backward", &srchbak);
  RegisterCommand("isrchbak", "ISEARCH_BACK", "Incremental search backward", &isrchbak);
  RegisterCommand("srchnxt", "SEARCH_NEXT", "Search next regexp", &srchnxt);
  RegisterCommand("srchprv", "SEARCH_PREV", "Search previous regexp", &srchprv);
  RegisterCommand("shiftl", "SHIFT_LEFT", "Shift screen left", &shiftl);
  RegisterCommand("shiftr", "SHIFT_RIGHT", "Shift screen right", &shiftr);
  RegisterCommand("col1R", "RIGHT", "Shift screen one column right", &col1R);
  RegisterCommand("col1L", "LEFT", "Shift screen one column", &col1L);
  RegisterCommand("setEnv", "SETENV", "Set environment variable", &setEnv);
  RegisterCommand("pipeBuf", "PIPE_BUF", "Send rendered document to pipe", &pipeBuf);
  RegisterCommand("pipesh", "PIPE_SHELL", "Execute shell command and browse", &pipesh);
  RegisterCommand("readsh", "READ_SHELL", "Execute shell command and load", &readsh);
  RegisterCommand("execsh", "EXEC_SHELL SHELL", "Execute shell command", &execsh);
  RegisterCommand("ldfile", "LOAD", "Load local file", &ldfile);
  RegisterCommand("ldhelp", "HELP", "View help", &ldhelp);
  RegisterCommand("movL", "MOVE_LEFT", "Move cursor left (a half screen shift at the left edge)", &movL);
  RegisterCommand("movL1", "MOVE_LEFT1", "Move cursor left (1 columns shift at the left edge)", &movL1);
  RegisterCommand("movD", "MOVE_DOWN", "Move cursor down (a half screen scroll at the end of screen)", &movD);
  RegisterCommand("movD1", "MOVE_DOWN1", "Move cursor down (1 line scroll at the end of screen)", &movD1);
  RegisterCommand("movU", "MOVE_UP", "Move cursor up (a half screen scroll at the top of screen)", &movU);
  RegisterCommand("movU1", "MOVE_UP1", "Move cursor up (1 line scrol at the top of screen)", &movU1);
  RegisterCommand("movR", "MOVE_RIGHT", "Move cursor right (a half screen shift at the right edge)", &movR);
  RegisterCommand("movR1", "MOVE_RIGHT1", "Move cursor right (1 columns shift at the right edge)", &movR1);
  RegisterCommand("movLW", "PREV_WORD", "Move to previous word", &movLW);
  RegisterCommand("movRW", "NEXT_WORD", "Move to next word", &movRW);
  RegisterCommand("quitfm", "ABORT EXIT", "Quit w3m without confirmation", &quitfm);
  RegisterCommand("qquitfm", "QUIT", "Quit w3m", &qquitfm);
  RegisterCommand("selBuf", "SELECT", "Go to buffer selection panel", &selBuf);
  RegisterCommand("susp", "INTERRUPT SUSPEND", "Stop loading document", &susp);
  RegisterCommand("goLine", "GOTO_LINE", "Go to specified line", &goLine);
  RegisterCommand("goLineF", "BEGIN", "Go to the first line", &goLineF);
  RegisterCommand("goLineL", "END", "Go to the last line", &goLineL);
  RegisterCommand("linbeg", "LINE_BEGIN", "Go to the beginning of line", &linbeg);
  RegisterCommand("linend", "LINE_END", "Go to the end of line", &linend);
  RegisterCommand("editBf", "EDIT", "Edit current document", &editBf);
  RegisterCommand("editScr", "EDIT_SCREEN", "Edit currently rendered document", &editScr);
  RegisterCommand("_mark", "MARK", "Set/unset mark", &_mark);
  RegisterCommand("nextMk", "NEXT_MARK", "Move to next word", &nextMk);
  RegisterCommand("prevMk", "PREV_MARK", "Move to previous mark", &prevMk);
  RegisterCommand("reMark", "REG_MARK", "Set mark using regexp", &reMark);
  RegisterCommand("followI", "VIEW_IMAGE", "View image", &followI);
  RegisterCommand("submitForm", "SUBMIT", "Submit form", &submitForm);
  RegisterCommand("topA", "LINK_BEGIN", "Go to the first link", &topA);
  RegisterCommand("lastA", "LINK_END", "Go to the last link", &lastA);
  RegisterCommand("nextA", "NEXT_LINK", "Move to next link", &nextA);
  RegisterCommand("prevA", "PREV_LINK", "Move to previous link", &prevA);
  RegisterCommand("nextVA", "NEXT_VISITED", "Move to next visited link", &nextVA);
  RegisterCommand("prevVA", "PREV_VISITED", "Move to previous visited link", &prevVA);
  RegisterCommand("followA", "GOTO_LINK", "Go to current link", &followA);
  RegisterCommand("nextL", "NEXT_LEFT", "Move to next left link", &nextL);
  RegisterCommand("nextLU", "NEXT_LEFT_UP", "Move to next left (or upward) link", &nextLU);
  RegisterCommand("nextR", "NEXT_RIGHT", "Move to next right link", &nextR);
  RegisterCommand("nextRD", "NEXT_RIGHT_DOWN", "Move to next right (or downward) link", &nextRD);
  RegisterCommand("nextD", "NEXT_DOWN", "Move to next downward link", &nextD);
  RegisterCommand("nextU", "NEXT_UP", "Move to next upward link", &nextU);
  RegisterCommand("nextBf", "NEXT", "Move to next buffer", &nextBf);
  RegisterCommand("prevBf", "PREV", "Move to previous buffer", &prevBf);
  RegisterCommand("backBf", "BACK", "Back to previous buffer", &backBf);
  RegisterCommand("deletePrevBuf", "DELETE_PREVBUF", "Delete previous buffer (mainly for local-CGI)", &deletePrevBuf);
  RegisterCommand("goURL", "GOTO", "Go to URL", &goURL);
  RegisterCommand("gorURL", "GOTO_RELATIVE", "Go to relative URL", &gorURL);
  RegisterCommand("ldBmark", "BOOKMARK VIEW_BOOKMARK", "Read bookmark", &ldBmark);
  RegisterCommand("adBmark", "ADD_BOOKMARK", "Add current page to bookmark", &adBmark);
  RegisterCommand("ldOpt", "OPTIONS", "Option setting panel", &ldOpt);
  RegisterCommand("msgs", "MSGS", "Display error messages", &msgs);
  RegisterCommand("pginfo", "INFO", "View info of current document", &pginfo);
  RegisterCommand("linkMn", "LINK_MENU", "Popup link element menu", &linkMn);
  RegisterCommand("accessKey", "ACCESSKEY", "Popup acceskey menu", &accessKey);
  RegisterCommand("setOpt", "SET_OPTION", "Set option", &setOpt);
  RegisterCommand("listMn", "LIST_MENU", "Popup link list menu and go to selected link", &listMn);
  RegisterCommand("movlistMn", "MOVE_LIST_MENU", "Popup link list menu and move cursor to selected link", &movlistMn);
  RegisterCommand("linkLst", "LIST", "Show all links and images", &linkLst);
  RegisterCommand("cooLst", "COOKIE", "View cookie list", &cooLst);
  RegisterCommand("ldHist", "HISTORY", "View history of URL", &ldHist);
  RegisterCommand("svA", "SAVE_LINK", "Save link to file", &svA);
  RegisterCommand("svI", "SAVE_IMAGE", "Save image to file", &svI);
  RegisterCommand("svBuf", "PRINT SAVE_SCREEN", "Save rendered document to file", &svBuf);
  RegisterCommand("svSrc", "DOWNLOAD SAVE", "Save document source to file", &svSrc);
  RegisterCommand("peekURL", "PEEK_LINK", "Peek link URL", &peekURL);
  RegisterCommand("peekIMG", "PEEK_IMG", "Peek image URL", &peekIMG);
  RegisterCommand("curURL", "PEEK", "Peek current URL", &curURL);
  RegisterCommand("vwSrc", "SOURCE VIEW", "View HTML source", &vwSrc);
  RegisterCommand("reload", "RELOAD", "Reload buffer", &reload);
  RegisterCommand("reshape", "RESHAPE", "Re-render buffer", &reshape);
  RegisterCommand("docCSet", "CHARSET", "Change the current document charset", &docCSet);
  RegisterCommand("defCSet", "DEFAULT_CHARSET", "Change the default document charset", &defCSet);
  RegisterCommand("chkURL", "MARK_URL", "Mark URL-like strings as anchors", &chkURL);
  RegisterCommand("chkWORD", "MARK_WORD", "Mark current word as anchor", &chkWORD);
  RegisterCommand("chkNMID", "MARK_MID", "Mark Message-ID-like strings as anchors", &chkNMID);
  RegisterCommand("rFrame", "FRAME", "Render frame", &rFrame);
  RegisterCommand("extbrz", "EXTERN", "Execute external browser", &extbrz);
  RegisterCommand("linkbrz", "EXTERN_LINK", "View current link using external browser", &linkbrz);
  RegisterCommand("curlno", "LINE_INFO", "Show current line number", &curlno);
  RegisterCommand("dispI", "DISPLAY_IMAGE", "Restart loading and drawing of images", &dispI);
  RegisterCommand("stopI", "STOP_IMAGE", "Stop loading and drawing of images", &stopI);
  RegisterCommand("msToggle", "MOUSE_TOGGLE", "Toggle activity of mouse", &msToggle);
  RegisterCommand("mouse", "MOUSE", "mouse operation", &mouse);
  RegisterCommand("movMs", "MOVE_MOUSE", "Move cursor to mouse cursor (for mouse action)", &movMs);
  RegisterCommand("menuMs", "MENU_MOUSE", "Popup menu at mouse cursor (for mouse action)", &menuMs);
  RegisterCommand("tabMs", "TAB_MOUSE", "Move to tab on mouse cursor (for mouse action)", &tabMs);
  RegisterCommand("closeTMs", "CLOSE_TAB_MOUSE", "Close tab on mouse cursor (for mouse action)", &closeTMs);
  RegisterCommand("dispVer", "VERSION", "Display version of w3m", &dispVer);
  RegisterCommand("wrapToggle", "WRAP_TOGGLE", "Toggle wrap search mode", &wrapToggle);
  RegisterCommand("dictword", "DICT_WORD", "Execute dictionary command (see README.dict)", &dictword);
  RegisterCommand("dictwordat", "DICT_WORD_AT", "Execute dictionary command for word at cursor", &dictwordat);
  RegisterCommand("execCmd", "COMMAND", "Execute w3m command(s)", &execCmd);
  RegisterCommand("setAlarm", "ALARM", "Set alarm", &setAlarm);
  RegisterCommand("reinit", "REINIT", "Reload configuration files", &reinit);
  RegisterCommand("defKey", "DEFINE_KEY", "Define a binding between a key stroke and a user command", &defKey);
  RegisterCommand("newT", "NEW_TAB", "Open new tab", &newT);
  RegisterCommand("closeT", "CLOSE_TAB", "Close current tab", &closeT);
  RegisterCommand("nextT", "NEXT_TAB", "Move to next tab", &nextT);
  RegisterCommand("prevT", "PREV_TAB", "Move to previous tab", &prevT);
  RegisterCommand("tabA", "TAB_LINK", "Open current link on new tab", &tabA);
  RegisterCommand("tabURL", "TAB_GOTO", "Open URL on new tab", &tabURL);
  RegisterCommand("tabrURL", "TAB_GOTO_RELATIVE", "Open relative URL on new tab", &tabrURL);
  RegisterCommand("tabR", "TAB_RIGHT", "Move current tab right", &tabR);
  RegisterCommand("tabL", "TAB_LEFT", "Move current tab left", &tabL);
  RegisterCommand("ldDL", "DOWNLOAD_LIST", "Display download list panel", &ldDL);
  RegisterCommand("undoPos", "UNDO", "Cancel the last cursor movement", &undoPos);
  RegisterCommand("redoPos", "REDO", "Cancel the last undo", &redoPos);
  RegisterCommand("mainMn", "MAIN_MENU MENU", "Popup menu", &mainMn);
  RegisterCommand("selMn", "SELECT_MENU", "Popup buffer selection menu", &selMn);
  RegisterCommand("tabMn", "TAB_MENU", "Popup tab selection menu", &tabMn);

}
